artemis_name:           apache-artemis-2.14.0
artemis_archive_name:   "{{ artemis_name }}-bin.tar.gz"
artemis_download_dest:  /tmp/{{ artemis_archive_name }}
artemis_download_url:   https://archive.apache.org/dist/activemq/activemq-artemis/2.14.0/{{ artemis_archive_name }}
                        
artemis_username:       artemis
