---
storage_fs_type: ext4
storage_path: "{{ kafka_data_dir }}"

apache_mirror: http://apache.mirrors.tds.net
kafka_hosts: "{{ansible_fqdn}}:9092"
kafka_version: 0.10.2.1
scala_version: 2.11
run_mode: Deploy
skip_install: False

kafka_port: 9092
kafka_heap_opts: "-Xmx1G -Xms1G"
kafka_tarball_location: /tmp
kafka_tarball_name: "kafka_{{scala_version}}-{{kafka_version}}.tgz"
kafka_wait_for_period: 60
zookeeper_hosts: "127.0.0.1:2181"

verify: True
