global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
  evaluation_interval: 5s

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'receiver'
    static_configs:
      - targets:
{% for receiver in receivers %}
        - "{{hostvars[receiver]['ec2_private_ip_address']}}:{{ receiver_scrape_port}}"
{% endfor %}