---

- name: Add extras repository
  shell: "sudo yum-config-manager --enable extras"

- name: Install Java 11 via amazon-linux-extras packages
  shell: "sudo amazon-linux-extras install java-openjdk11 -y"