---
- name: setup group
  group: name={{kafka_group}} system=yes

- name: Setup user
  user: name={{kafka_user}} system=yes group={{kafka_group}}

- name: Uncompress the kafka tar
  unarchive: copy=no creates="/opt/kafka_{{scala_version}}-{{kafka_version}}" dest=/opt src="{{ kafka_tarball_location }}/{{ kafka_tarball_name }}"

- name: Link /opt/kafka to the right version
  file: path=/opt/kafka state=link src="/opt/kafka_{{scala_version}}-{{kafka_version}}"

- name: Detect if this is a systemd based system
  command: cat /proc/1/comm
  register: init
  changed_when: False

- set_fact: use_systemd=True
  when: init.stdout == 'systemd'
- set_fact: use_systemd=False
  when: init.stdout != 'systemd'

- name: create upstart config
  template: dest={{kafka_upstart_conf}} owner=root group=root mode=644 src=kafka.conf.j2
  notify:
    - restart kafka
  when: not use_systemd

- name: create systemd config
  template: dest={{kafka_systemd_service}} owner=root group=root mode=644 src=kafka.service.j2
  notify:
    - restart kafka
  when: use_systemd

- command: systemctl daemon-reload
  when: use_systemd

- name: Create data_dir
  file: path={{kafka_data_dir}} state=directory owner={{kafka_user}} group={{kafka_group}} mode=755

- name: Remove lost+found in the datadir
  file: path="{{kafka_data_dir}}/lost+found" state=absent

- name: Create log_dir
  file: path={{kafka_log_dir}} state=directory owner={{kafka_user}} group={{kafka_group}} mode=755

- name: link conf_dir to /opt/kafka/config
  file: path={{kafka_conf_dir}} state=link src=/opt/kafka/config

# Setup log4j.properties
- name: create log4j.properties
  template: dest="{{kafka_conf_dir}}/log4j.properties" owner={{kafka_user}} group={{kafka_group}} mode=644 src=log4j.properties.j2
  notify:
    - restart kafka

# Setup server.properties
- name: create server.properties
  template: dest="{{kafka_conf_dir}}/server.properties" owner={{kafka_user}} group={{kafka_group}} mode=640 src=server.properties.j2
  notify:
    - restart kafka

- meta: flush_handlers
