---
- include: stop.yml
  when: run_mode == 'Stop'

- include: prepare_storage.yml
  when: storage_device is defined

- include: install.yml
  when: not skip_install and ( run_mode == 'Install' or run_mode == 'Deploy' )

- include: configure.yml
  when: run_mode == 'Configure' or run_mode == 'Deploy'

- include: start.yml
  when: run_mode == 'Start' or run_mode == 'Deploy'
