---
- name: Enable and Start Kafka
  service: name=kafka state=started enabled=yes

- name: wait for kafka port
  wait_for: host={{kafka_listen_address| default('localhost')}} port={{kafka_port}} state=started timeout={{ kafka_wait_for_period }}
  when: verify
