---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 3, ec2_groups: [ 'ssh_access', 'default' ], aws_instance_type: t2.micro, ec2_tag_group: Mongo }

- hosts: mongo
  roles:
  - role: mongod