---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'grafana_access', 'default'], aws_instance_type: t2.large, ec2_tag_group: Prometheus, volume_size: 100 }

- hosts: prometheus
  become: true
  roles:
  - role: prometheus_grafana
