---

- name: Provision a set of instances
  ec2:
    key_name: "{{ key_name }}"
    group: "{{ ec2_groups }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_ami_id }}"
    vpc_subnet_id: "{{ subnet_external }}"
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    wait: true
    exact_count: "{{ count }}"
    assign_public_ip: true
    count_tag:
      group: "{{ ec2_tag_group }}"
    instance_tags:
      group: "{{ ec2_tag_group }}"
      kind: "mqperf-instance"
  register: ec2

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 10
    timeout: 640
    state: started
  with_items: "{{ ec2.instances }}"
  when: ec2.changed

- name: Provision and attach EBS volume
  ec2_vol:
    instance: "{{ item.id }}"
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volume_size: "{{ volume_size }}"
    volume_type: "gp2"
    delete_on_termination: yes
  with_items: "{{ ec2.instances }}"
  when: volume_size is defined and ec2.changed

- name: Refresh inventory
  meta: refresh_inventory
